# https://github.com/drdkadtr/gh-action-argocd-app-env/settings/actions/runners
name: self-hosted

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # https://github.com/actions/runner
  # https://github.com/atrakic/argocd-local-dev/settings/actions/runners/new
  self-hosted-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup infra
        run: |
          .github/self-hosted/setup.sh

      - name: Setup argocd and patch it
        run: |
          .github/self-hosted/install-argocd.sh

      - name: Wait for cluster to finish bootstraping
        run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

      - name: Install example application
        run: |
          kubectl apply -f ./applications/json-server/application.yaml

# TODO: use argocd commands to sync
